name: Release Test
on:
  workflow_dispatch: {}
jobs:
  goreleaser-snapshot:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Allow goreleaser to access older tag information.
        filter: blob:none
    - uses: actions/setup-go@v5
      with:
        go-version: stable
    - name: Import GPG Key
      run: gpg --batch --import <<< "$GPG_PRIVATE_KEY"
      env:
        GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v6
      with:
        args: release --clean --snapshot
