name: Unit Test
on:
  push: {}
jobs:
  unit-test:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version: stable
    - name: Unit Test
      run: go test -v ./...
